language: scala
scala:
 - 2.11.12
 - 2.12.8
 - 2.13.0
script:
  - |
    if [ "${TRAVIS_TAG:-}" != "" ]; then
      VERSION=$(echo "$TRAVIS_TAG" | sed 's/^v//')
    else
      VERSION=$(git log --format=%H -1)
    fi
  - sbt ++${TRAVIS_SCALA_VERSION}! 'set version in ThisBuild := "'$VERSION'"' clean test
after_success:
  - |
    if [ $TRAVIS_PULL_REQUEST == "false" ] && ([ "${TRAVIS_BRANCH:-}" == "master" ] || [ "${TRAVIS_TAG:-}" != "" ]); then
      export BINTRAY_REPO=${BINTRAY_REPO:-scala-hedgehog-maven}
      sbt ++${TRAVIS_SCALA_VERSION}! \
        'set version in ThisBuild := "'$VERSION'"' \
        'set publishMavenStyle in ThisBuild := true' \
        'set bintrayRepository in ThisBuild := "'$BINTRAY_REPO'"' \
        publish
      if [ "${TRAVIS_TAG:-}" != "" ]; then
        export VERSION
        ./ci/bintray_maven_central_sync
      fi
    fi

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
