language: scala
scala:
 - 2.10.7
 - 2.11.12
 - 2.12.8
 - 2.13.0
script:
  - |
    if [ "${TRAVIS_TAG:-}" != "" ]; then
      VERSION=$(echo "$TRAVIS_TAG" | sed 's/^v//')
    else
      VERSION=$(git log --format=%H -1)
    fi
  - sbt ++$TRAVIS_SCALA_VERSION 'set version in ThisBuild := "'$VERSION'"' test
after_success:
  - |
    if [ $TRAVIS_PULL_REQUEST == "false" ] && ([ "${TRAVIS_BRANCH:-}" == "master" || [ "${TRAVIS_TAG:-}" != "" ]); then
      sbt ++$TRAVIS_SCALA_VERSION 'set version in ThisBuild := "'$VERSION'"' "set publishMavenStyle in ThisBuild := false" publish
      sbt ++$TRAVIS_SCALA_VERSION 'set version in ThisBuild := "'$VERSION'"' "set publishMavenStyle in ThisBuild := true" publish
    fi
